# recover

recover函数用于恢复panic，它只能在defer函数中使用。当程序发生panic时，会自动调用defer函数，并将panic传递给recover函数。recover函数会返回panic的值，如果没有panic发生，recover函数会返回nil。

```go
func main() {
    defer func() {
        if err := recover(); err!= nil {
            fmt.Println("panic:", err)
        }
    }()
    panic("something went wrong")
}
```

在上面的代码中，当panic发生时，会自动调用defer函数，并将panic的值传递给recover函数。如果recover函数返回nil，则程序正常运行；如果recover函数返回非nil值，则程序会打印panic的值。      